CREATE TABLE match_results (
  id bigserial not null primary key,
  home_team varchar not null,
  home_team_id bigserial not null,
  full_time_home_team_goals smallint not null,
  half_time_home_team_goals smallint not null,
  home_team_shots smallint not null,
  home_team_shots_on_target smallint not null,
  home_team_corners smallint not null,
  home_team_fouls_committed smallint not null,
  home_team_yellow_cards smallint not null,
  home_team_red_cards smallint not null,
  away_team varchar not null,
  away_team_id bigserial not null,
  full_time_away_team_goals smallint not null,
  half_time_away_team_goals smallint not null,
  away_team_shots smallint not null,
  away_team_shots_on_target smallint not null,
  away_team_corners smallint not null,
  away_team_fouls_committed smallint not null,
  away_team_yellow_cards smallint not null,
  away_team_red_cards smallint not null,
  full_time_result varchar not null,
  half_time_result varchar not null,
  date_start timestamp not null,
  league_id bigserial not null
)